# Generated by Django 3.1.7 on 2021-04-25 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalToHumidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(max_length=50)),
                ('minHumidity', models.IntegerField()),
                ('maxHumidity', models.IntegerField()),
                ('climate', models.CharField(blank=True, choices=[('0', 'NA'), ('1', 'Desert'), ('2', 'Temperate'), ('3', 'Tropical / Semi-Aquatic')], default='0', max_length=1)),
            ],
            options={
                'ordering': ['specie'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Terrarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(default='test', max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('climate', models.CharField(blank=True, choices=[('0', 'NA'), ('1', 'Desert'), ('2', 'Temperate'), ('3', 'Tropical / Semi-Aquatic')], default='0', max_length=1)),
                ('minHumidity', models.IntegerField(default='')),
                ('maxHumidity', models.IntegerField(default='')),
                ('currentHumidity', models.IntegerField(default='0')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humidityControl.animaltohumidity')),
            ],
        ),
        migrations.CreateModel(
            name='ValveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('actionRequested', models.CharField(blank=True, choices=[('0', 'Close'), ('1', 'Open')], default='0', help_text="Valve action requested to the terrarium's valve", max_length=1)),
                ('terrarium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humidityControl.terrarium')),
            ],
        ),
        migrations.CreateModel(
            name='HumidityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.IntegerField(help_text='Humidity value measured at this moment')),
                ('terrarium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humidityControl.terrarium')),
            ],
        ),
    ]
