# Generated by Django 3.1.7 on 2021-03-29 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humidityControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalToHumidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(max_length=50)),
                ('minHumidity', models.IntegerField()),
                ('maxHumidity', models.IntegerField()),
                ('climate', models.CharField(blank=True, choices=[('0', 'NA'), ('1', 'Desert'), ('2', 'Temperate'), ('3', 'Tropical / Semi-Aquatic')], default='0', max_length=1)),
            ],
            options={
                'ordering': ['specie'],
            },
        ),
        migrations.CreateModel(
            name='HumidityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('humidity', models.IntegerField(help_text='Humidity value measured at this moment')),
            ],
        ),
        migrations.CreateModel(
            name='Terrarium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='The nickname you give to your terrarium', max_length=30)),
                ('animal', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Your username', max_length=20)),
                ('terrariums', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humidityControl.terrarium')),
            ],
        ),
        migrations.CreateModel(
            name='ValveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('actionRequested', models.CharField(blank=True, choices=[('0', 'Closed'), ('1', 'Close-Opened'), ('2', 'Open-Closed'), ('3', 'Opened')], default='0', help_text="Valve action requested to the terrarium's valve", max_length=1)),
                ('terrarium', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humidityControl.terrarium')),
            ],
        ),
        migrations.DeleteModel(
            name='HumidityControl',
        ),
        migrations.AddField(
            model_name='humiditylog',
            name='terrarium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humidityControl.terrarium'),
        ),
    ]
