# Generated by Django 3.1.7 on 2021-04-28 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humidityControl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrarium',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='terrarium',
            name='maxHumidity',
        ),
        migrations.RemoveField(
            model_name='terrarium',
            name='minHumidity',
        ),
    ]
