# Generated by Django 3.1.7 on 2021-05-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humidityControl', '0002_auto_20210428_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrarium',
            name='setHumidity',
            field=models.IntegerField(default='0'),
        ),
    ]
