# Generated by Django 3.1.7 on 2021-04-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humidityControl', '0004_auto_20210417_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrarium',
            name='climate',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='terrarium',
            name='currentHumidity',
            field=models.IntegerField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='terrarium',
            name='maxHumidity',
            field=models.IntegerField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='terrarium',
            name='minHumidity',
            field=models.IntegerField(default='', max_length=3),
        ),
    ]
