# Generated by Django 3.1.7 on 2021-04-17 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humidityControl', '0005_auto_20210417_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrarium',
            name='animal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='humidityControl.animaltohumidity'),
        ),
        migrations.AlterField(
            model_name='terrarium',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
