# Generated by Django 3.1.7 on 2021-04-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humidityControl', '0006_auto_20210417_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humidityControl.user'),
        ),
    ]
