# Generated by Django 3.1.7 on 2021-04-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humidityControl', '0011_auto_20210421_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrarium',
            name='owner',
            field=models.CharField(default='test', max_length=30),
        ),
    ]
